### ISSUE TITLE
i can't use this data 

### ISSUE THREAD

**Issue by Denjjo** [couchbase/docs-sdk-go#112]
how i can parse this data :-
map[example:map[firstname:NIC lastname:Raboy socialmedia:[map[link:http:www.com title:Twitter] map[link:http:www.com title:Github]]]]

**Comment by RichardSmedley** [comment]
Could we have a little more context for your question, and how it relates to the documentation in this repo, please?

**Comment by Denjjo** [comment]
This is the code
package main

import (
	"encoding/json"
	"fmt"

	"github.com/couchbase/gocb/v2"
)

 func main() {
	cluster, _ := gocb.Connect(
		"couchbase://localhost",
		gocb.ClusterOptions{
			Username: "admin",
			Password: "admin@123",
		})
	query := "SELECT * FROM `example` LIMIT 10;"
	rows, err := cluster.Query(query, &gocb.QueryOptions{})
	if err != nil {
		panic(err)
	}
	// check query was successful
	var h map[string]interface{}
	err = rows.One(&h)
	if err != nil {
		panic(err)
	}
	fmt.Print(h)

**Comment by maria-robobug** [comment]
Hi, what error are you getting when you run the code? 
Maybe a `struct` would be more suited for representing the data if it is quite nested/complex?

I think it might be easier to open a doc issue here if you find that the documentation might not be clear enough:
https://docs.couchbase.com/home/contribute/index.html#reporting-bugs-and-requesting-enhancements

We also have a forum if you want to raise issues related to the `go-sdk`, which might be more suited for the problem you are having: https://forums.couchbase.com/c/go-sdk/23

**Comment by RichardSmedley** [comment]
Closing this as a GH issue, as I believe Maria has covered the substantive issue.
Please do consider opening a DOC ticket on our JIRA, as linked above, if you think the transcoders documentation could be improved.
All the best with your project!
